apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: codeserver
  name: codeserver
  namespace: homeautomation
spec:
  ports:
  - name: "8443"
    port: 8443
    targetPort: 8443
  selector:
          io.kompose.service: codeserver 
status:
  loadBalancer: {}
