 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sickchill-deployment
   namespace: mediaserver
   labels:
     app: sickchill
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: sickchill
   template:
     metadata:
       labels:
         app: sickchill
     spec:
      containers:
         - name: sickchill
           image: linuxserver/sickchill
           env:
             - name: PGID
               value: "1000"
             - name: PUID
               value: "1000"
           ports:
             - containerPort: 8081
           volumeMounts:
             - mountPath: /config
               name: sickchill-config
             - mountPath: /downloads
               name: sickchill-downloads
             - mountPath: /incomplete-downloads
               name: sickchill-incomplete
             - mountPath: /tv
               name: sickchill-tv
      volumes:
        - name: sickchill-config
          nfs:
            server: 192.168.178.33
            path: /volume1/sickchill-config
        - name: sickchill-downloads
          nfs:
            server: 192.168.178.33
            path: /volume1/openflixr/
        - name: sickchill-incomplete
          nfs:
            server: 192.168.178.33
            path: /volume1/openflixr/incomplete
        - name: sickchill-tv
          nfs:
            server: 192.168.178.33
            path: /volume1/Series
