kind: Service
apiVersion: v1
metadata:
  labels:
    app: sabnzbd
  name: sabnzbd-service
  namespace: mediaserver
spec:
  selector:
    app: sabnzbd
  ports:
  - name: "6789"
    port: 6789
    targetPort: 6789
status:
    loadBalancer: {}
