apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: homeassistant
  name: homeassistant
  namespace: homeautomation
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: homeassistant
    spec:
      containers:
      - image: homeassistant/home-assistant
        imagePullPolicy: Always
        name: homeassistant
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: TZ
          value: "Europe/Amsterdam"
        ports:
        - containerPort: 8123
        volumeMounts:
        - mountPath: /config
          name: homeassistant-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: homeassistant-config
        nfs:
         server: 192.168.178.33
         path: "/volume1/openflixr/homeassistant/"
status: {}
