apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: radarr
  name: radarr
  namespace: mediaserver
spec:
  selector:
    io.kompose.service: radarr
  ports:
  - protocol: TCP
    port: 7878
    targetPort: 7878
  type: NodePort
