apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: experimental
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
