apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
  namespace: homeautomation
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb
    spec:
       containers:
       - name: influxdb
         image: influxdb
         envFrom: 
         - secretRef:
             name: influxdb-ha-creds
         ports:
         - containerPort: 8086
         - containerPort: 8083
         resources: {}
         volumeMounts:
         - mountPath: /var/lib/influxdb
           name: fluxconfig 
       volumes:
       - name: fluxconfig
         nfs:
           server: 192.168.178.33
           path: "/volume1/influxdb/"
status: {}
